use-sort:
    group:
        - _main
    group-type: each
    sort-type: alph
    sort-direction: asc

header: |
    /*
     * This file is part of the desarrolla2 test bundle package
     *
     * Copyright (c) 2017-2018 Devtia Soluciones
     *
     * For the full copyright and license information, please view the LICENSE
     * file that was distributed with this source code.
     *
     * @author Daniel González <daniel@devtia.com>
     */