services:

    desarrolla2_test.command_php_unit.statistics_command:
        class: Desarrolla2\TestBundle\Command\PhpUnit\StatisticsCommand
        arguments: [ '@desarrolla2.cache', '@kernel', '@router' ]
        tags:
            - { name: console.command }
